version: '3'

services:
  redis:
    image: redis:rc-alpine3.11
    ports:
      - "6379:6379"
  database:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /private/var/lib/postgresql:/var/lib/postgresql
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: crawlers
